### ISSUE TITLE
Key frames in `@keyframes` are processed as CSS selectors

### ISSUE THREAD

**Issue by victor-homyakov** [eprev/specificity#16]
Parsing/exploring CSS

```CSS
@keyframes animated-bubble-pointer {
    0% {box-shadow: 0 2px 7px rgba(0, 0, 0, .2);}
    100% {box-shadow: 0 2px 8px rgba(0, 0, 0, .2);}
}

@-moz-keyframes animated-bubble-pointer {
    0% {box-shadow: 0 2px 7px rgba(0, 0, 0, .2);}
    100% {box-shadow: 0 2px 8px rgba(0, 0, 0, .2);}
}

@-webkit-keyframes animated-bubble-pointer {
    0% {box-shadow: 0 2px 7px rgba(0, 0, 0, .2);}
    100% {box-shadow: 0 2px 8px rgba(0, 0, 0, .2);}
}
```

produces following report:

```
  ┌──────────┬─────────────┬───┬───────────────────┐
  │ selector │ specificity │ ! │ location          │
  ├──────────┼─────────────┼───┼───────────────────┤
  │ 100%     │       0,0,1 │ 0 │ keyframe.css:13|5 │
  │ 0%       │       0,0,1 │ 0 │ keyframe.css:12|5 │
  │ 100%     │       0,0,1 │ 0 │ keyframe.css:8|5  │
  │ 0%       │       0,0,1 │ 0 │ keyframe.css:7|5  │
  │ 100%     │       0,0,1 │ 0 │ keyframe.css:3|5  │
  │ 0%       │       0,0,1 │ 0 │ keyframe.css:2|5  │
  └──────────┴─────────────┴───┴───────────────────┘
```

`xxx%`, `from`, `to` are processed as CSS selectors.
